Repository mul-meong/backend-notification, pull requests merged in 2024-12, with the labels that each got.

#5 [🚀 Notification] CI/CD 환경 구축
  .github/workflows/cicd.yaml
  Dockerfile
  build.gradle
Labels: 👷 chore, 🚀 deploy

#9 [🚑️ notification] config 에러 Resolve
  build.gradle
Labels: 🚑️ hotfix

#8 [🔀 notification] build.gradle 수정
  build.gradle
Labels: ♻️ refactor
